export const FETCH_POSTS = 'FETCH_POSTS';
export const TOGGLE_COMMENT = 'TOGGLE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';